name: Build and Upload CraftBukkit

on:
  workflow_dispatch:

jobs:
  build-craftbukkit:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        version: [
          '1.20.1', '1.19.4', '1.19.3', '1.19.2', '1.19.1', '1.19', '1.18.2', '1.18.1', '1.18', '1.17.1',
          '1.17', '1.16.5', '1.16.4', '1.16.3', '1.16.2', '1.16.1', '1.15.2', '1.15.1','1.13.2', '1.13.1', '1.13', '1.12.2',
          '1.12.1', '1.12', '1.11.2', '1.11', '1.10.2', '1.9.4', '1.9.2', '1.9', '1.8.8', '1.8.3', '1.8'
        ]

    steps:
      - name: Cache Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Configure AWS CLI for S3
        run: |
          aws configure set aws_access_key_id ${{ secrets.S3_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.S3_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1

      - name: Set up JDK for Minecraft versions below 1.17
        if: |
          startsWith(matrix.version, '1.8') || 
          startsWith(matrix.version, '1.9') || 
          startsWith(matrix.version, '1.10') || 
          startsWith(matrix.version, '1.11') || 
          startsWith(matrix.version, '1.12') || 
          startsWith(matrix.version, '1.13') || 
          startsWith(matrix.version, '1.15') || 
          startsWith(matrix.version, '1.16')
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Set up JDK for Minecraft version 1.17
        if: matrix.version == '1.17'
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Set up JDK for Minecraft version 1.17.1 and above
        if: |
          matrix.version == '1.17.1' || 
          startsWith(matrix.version, '1.18') || 
          startsWith(matrix.version, '1.19') ||
          startsWith(matrix.version, '1.20')
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Download BuildTools.jar
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Build and Upload CraftBukkit JARs
        run: |
          java -jar BuildTools.jar --rev ${{ matrix.version }} --compile craftbukkit
          
          JAR_NAME=craftbukkit-${{ matrix.version }}.jar
          
          aws s3 cp $JAR_NAME s3://$S3_BUCKET_NAME/minecraft-jars/server/craftbukkit/$JAR_NAME --endpoint-url $S3_ENDPOINT
          echo "Successfully uploaded Spigot version ${{ matrix.version }} to S3!"

        env:
          S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}